name: Build LaTeX Resumes

on:
  push:
    branches: [main]
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true || github.event_name == 'push'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 0

      - name: Set up TeX Live
        uses: xu-cheng/latex-action@v2
        with:
          root_file: ''
          latexmk_use_xelatex: true
          # Add fallback options if needed
          latexmk_shell_escape: true

      - name: Create output directory
        run: mkdir -p output

      - name: Compile Professional Resume
        continue-on-error: true
        run: |
          cd professional
          pdflatex -interaction=nonstopmode main.tex
          if [ -f main.pdf ]; then
            mv main.pdf ../output/professional_resume.pdf
          else
            echo "Professional resume compilation failed"
            exit 1
          fi

      - name: Compile Academic Resume
        continue-on-error: true
        run: |
          cd academic
          pdflatex -interaction=nonstopmode main.tex
          if [ -f main.pdf ]; then
            mv main.pdf ../output/academic_resume.pdf
          else
            echo "Academic resume compilation failed"
            exit 0
          fi

      - name: List output directory
        run: ls -la output/

      - name: Upload PDFs as artifacts
        uses: actions/upload-artifact@v3.1.2
        with:
          name: compiled-resumes
          path: output/*.pdf
          if-no-files-found: warn

      - name: Commit and push PDFs to repository
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          if [ -f output/professional_resume.pdf ] || [ -f output/academic_resume.pdf ]; then
            git add output/*.pdf
            git commit -m "Update compiled resume PDFs" || echo "No changes to commit"
            git push || echo "Push failed, possibly due to permissions"
          else
            echo "No PDFs to commit"
          fi

# Comment out the preview section until the basic workflow is working
# We can add it back later
#  preview_pdf:
#    needs: build_latex
#    runs-on: ubuntu-latest
#    if: github.event_name == 'pull_request' && github.event.action != 'closed'
#    steps:
#      - name: Download compiled PDFs
#        uses: actions/download-artifact@v3.1.2
#        with:
#          name: compiled-resumes
#
#      - name: Comment PR with PDF links
#        uses: actions/github-script@v6
#        with:
#          github-token: ${{secrets.GITHUB_TOKEN}}
#          script: |
#            const fs = require('fs');
#            const issue_number = context.issue.number;
#
#            github.rest.issues.createComment({
#              owner: context.repo.owner,
#              repo: context.repo.repo,
#              issue_number: issue_number,
#              body: 'PDF preview ready!\nCheck the artifacts of this build for compiled PDFs.'
#            });
