name: Build LaTeX Resumes

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_latex:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create output directory
        run: mkdir -p output

      - name: Compile Professional Resume
        uses: xu-cheng/latex-action@v2
        with:
          root_file: professional/main.tex
          working_directory: ./
          args: '-pdf -file-line-error -halt-on-error -interaction=nonstopmode'

      - name: Move Professional PDF to output
        run: mv professional/main.pdf output/professional_resume.pdf

      - name: Compile Academic Resume
        uses: xu-cheng/latex-action@v2
        with:
          root_file: academic/main.tex
          working_directory: ./
          args: '-pdf -file-line-error -halt-on-error -interaction=nonstopmode'

      - name: Move Academic PDF to output
        run: mv academic/main.pdf output/academic_resume.pdf

      - name: Upload PDFs as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: compiled-resumes
          path: output/*.pdf

      - name: Commit and push PDFs to repository
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add output/*.pdf
          git commit -m "Update compiled resume PDFs" || echo "No changes to commit"
          git push
